blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('blogs.urls')),
]

blogs/urls.py
"""Определение схемы url для приложения blogs"""
from django.urls import path
from . import views

app_name = 'blogs'
urlpatterns = [
    # Домашняя страница
    path('', views.index, name='index'),
    # Страница для добавления новой записи
    path('new_post/', views.new_post, name='new_post'),
    path('edit_post/<int:texts_id>/', views.edit_post, name='edit_post'),
]

users/urls.py
"""Определяет схемы url для пользователей"""
from django.urls import path, include
from . import views

app_name = 'users'

urlpatterns = [
	# Включить url для авторизации по умолчанию
	path('', include('django.contrib.auth.urls')),
	# Страница регистрации
	path('register/', views.register, name='register'),
]

blogs/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
 
class BlogPost(models.Model):
	"""Содержит заголовок, текст и дату"""
	title = models.CharField(max_length = 200)
	text = models.TextField()
	date_added = models.DateTimeField(auto_now_add=True)
	owner = models.ForeignKey(User, on_delete=models.CASCADE)


	def __str__(self):
		return self.title

users/models.py
from django.db import models

# Create your models here.

blogs/forms.py
from django import forms 
from .models import BlogPost

class BlogPostForm(forms.ModelForm):
	class Meta:
		model = BlogPost
		fields = ['title', 'text']
		labels = {'text': ''}

blogs/views.py
from django.shortcuts import render, redirect
from .models import BlogPost
from .forms import BlogPostForm
from django.contrib.auth.decorators import login_required
from django.http import Http404
# Create your views here.

def index(request):
	"""Домашняя страница приложения Blogs"""
	title = BlogPost.objects.all()
	text = BlogPost.objects.order_by('-date_added')
	context = {'title': title, 'text': text}
	return render(request, 'blogs/index.html', context)

@login_required
def new_post(request):
	"""Определяет новую запись"""
	if request.method != 'POST':
		# Данные не отправились создается пустая форма
		form = BlogPostForm()
	else:
		# Отправленны данные POST; обработать данные
		form = BlogPostForm(data=request.POST)
		if form.is_valid():
			new_text = form.save(commit=False)
			new_text.owner = request.user
			new_text.save()
			return redirect('blogs:index')

	# Вывести пустую или недействительную форму
	context = {'form': form}
	return render(request, 'blogs/new_post.html', context)

@login_required
def edit_post(request, texts_id):
	texts = BlogPost.objects.get(id=texts_id)
	if request.method != 'POST':
		form = BlogPostForm(instance=texts)
	else:
		form = BlogPostForm(instance=texts, data=request.POST)
		if form.is_valid():
			if texts.owner != request.user:
				raise Http404
			form.save()
			return redirect('blogs:index')

	context = {'texts': texts, 'form': form}
	return render(request, 'blogs/edit_post.html', context)

users/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
# Create your views here.

def register(request):
	"""Регистрирует нового пользователя"""
	if request.method != 'POST':
		# Выводит пустую форму.
		form = UserCreationForm()
	else:
		# Обработка заполненной формы
		form = UserCreationForm(data=request.POST)
		if form.is_valid():
			new_user = form.save()
			# Выполнение входа и перенапровление на домашнюю страницу
			login(request, new_user)
			return redirect('blogs:index')

	# Выводит пустую или недействительную форму
	context = {'form': form}
	return render(request, 'registration/register.html', context)

blogs/templates/blogs/base.html
{% load bootstrap4 %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, 
    shrink-to-fit=no">
  <title>My Blog</title>

  {% bootstrap_css %}
  {% bootstrap_javascript jquery='full' %}
</head>
<body>
  <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
    <a class="navbar-brand" href="{% url 'blogs:index' %}">My Blog</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse"
      data-target="#navbarCollapse" aria-controls="navbarCollapse">
      <span class="navbar-toggler-icon"></span></button>

    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav ml-auto">
        {% if user.is_authenticated %}
          <li class="nav-item">
            <span class="navbar-text">Hello, {{ user.username }}!</span>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:logout' %}">Выход</a>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:register' %}">Регистрация</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:login' %}">Войти</a>
          </li>
        {% endif %}
      </ul>
    </div>
  </nav>

  <main role="main" class="container">
    <div class="pb-2 mb-2 border-bottom">
      {% block page_header %}{% endblock page_header %}
    </div>
    <div>
      {% block content %}{% endblock content %}
    </div>
  </main>
</body>
</html>

blogs/templates/blogs/edit_post.html
{% extends "blogs/base.html" %}

{% load bootstrap4 %}

{% block page_header %}
  <h3>Внесите изменения в запись</h3>
{% endblock page_header %}

{% block content %}
  <form method="post" action="{% url 'blogs:edit_post' texts.id %}" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button name="submit" class="btn btn-primary">Сохранить изменения</button>
    {% endbuttons %}

    <input type="hidden" name="next"
      value="{% url 'blogs:index' %}" />
  </form>
{% endblock content %}

blogs/templates/blogs/index.html
{% extends 'blogs/base.html' %}

{% block content %}
  <p><a class="btn btn-lg btn-primary" href="{% url 'blogs:new_post' %}">Создать новую запись</a></p>
    <div class="jumbotron">
      {% for texts in text %}
        <div class="card mb-3">
          <p class="card-header">
            {{ texts }}
            {{ texts.date_added|date:'M d, Y H:i' }}
            <small><a href="{% url 'blogs:edit_post' texts.id %}">Изменить пост</a></small>
          </p>
          <div class="card-body">
            <p>{{ texts.text|linebreaks }}</p>
          </div>
        </div>
      {% endfor %}
    </div>
{% endblock content %}

blogs/templates/blogs/new_post.html
{% extends "blogs/base.html" %}

{% load bootstrap4 %}

{% block page_header %}
  <h3>Создайте новую запись</h3>
{% endblock page_header %}

{% block content %}
  <form method="post" action="{% url 'blogs:new_post' %}" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button name="submit" class="btn btn-primary">Добавить запись</button>
    {% endbuttons %}

    <input type="hidden" name="next"
      value="{% url 'blogs:index' %}" />
  </form>
{% endblock content %}